In [259]:
import pandas
import numpy

# Задачи по pandas

## Задача №1:
Найти евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [260]:
first_series = pandas.Series([2, 4, 6, 8])
second_series = pandas.Series([1, 3, 5, 7])

### Решение:
> Для проверки решения используем функцию NumPy.

In [261]:
using_numpy = numpy.linalg.norm(first_series - second_series)
without_numpy = sum((first_series - second_series) ** 2) ** .5
print(f'\t- Контрольное значение: {using_numpy};\n\t- Результат вычисления: {without_numpy}.')

	- Контрольное значение: 2.0;
	- Результат вычисления: 2.0.


## Задача №2:
Найти максимально возможное абсолютное значение корреляции каждого столбца с другими столбцами в df.

Ввод:

In [262]:
data_frame = pandas.DataFrame(numpy.random.randint(1, 100, 16).reshape(4, 4), columns=list('abcd'), index=list('1234'))
print(data_frame)

    a   b   c   d
1  80   5  47   7
2  39  55  70   3
3  60  50  44  53
4  60   5  35  63


### Решение:

In [263]:
abs_corr = numpy.abs(data_frame.corr())
max_corr = abs_corr.apply(lambda field: sorted(field)[-2])
rounded_list = numpy.round(max_corr.tolist(), 2)
result = pandas.DataFrame(rounded_list.reshape(1, 4), index=['max(abs(corr))'], columns=data_frame.columns)
print(f'Максимальное значение корреляции для каждого столбца:\n{result}')


Максимальное значение корреляции для каждого столбца:
                   a     b     c     d
max(abs(corr))  0.74  0.74  0.79  0.79


## Задача №3:
Нормализуйте все столбцы df путём вычитания среднего значения столбца и деления на стандартное отклонение.
Сделайте так, чтобы все значения в df находились в диапазоне от 0 до 1.

Ввод:

In [264]:
data_frame = pandas.DataFrame(numpy.random.randint(1, 100, 16).reshape(4, 4), index=list('1234'), columns=list('abcd'))
print(data_frame)

    a   b   c   d
1   3  89  59  72
2  51  27  79  40
3  67  76  87  37
4  93   6  10  61


### Решение:

#### Часть 1-я:

In [265]:
first_result = data_frame.apply(lambda field: ((field - field.mean()) / field.std()).round(2))
print(first_result)

      a     b     c     d
1 -1.33  1.00  0.01  1.16
2 -0.07 -0.57  0.59 -0.74
3  0.36  0.67  0.82 -0.92
4  1.04 -1.10 -1.41  0.51


#### Часть 2-я:

In [266]:
second_result = data_frame.apply(lambda field: ((field.max() - field) / (field.max() - field.min())).round(2))
print('Вторая часть\n', second_result)

Вторая часть
       a     b     c     d
1  1.00  0.00  0.36  0.00
2  0.47  0.75  0.10  0.91
3  0.29  0.16  0.00  1.00
4  0.00  1.00  1.00  0.31


## Задача №4:

Объедините df1 и df2 по столбцам fruit-frukt и weight-ves.

Ввод:

In [267]:
first_source = pandas.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                                 'weight': ['low', 'medium', 'high'] * 3,
                                 'price': numpy.random.randint(0, 100, 9)})

second_source = pandas.DataFrame({'frukt': ['apple', 'banana', 'melon'] * 2,
                                  'ves': ['low', 'high'] * 3,
                                  'price': numpy.random.randint(0, 100, 6)})
print(f'df1:\n{first_source}\n\n df2:\n{second_source}')

df1:
    fruit  weight  price
0   apple     low     81
1  banana  medium     64
2  orange    high     14
3   apple     low     48
4  banana  medium     24
5  orange    high     86
6   apple     low     80
7  banana  medium     24
8  orange    high     55

 df2:
    frukt   ves  price
0   apple   low     22
1  banana  high      6
2   melon   low     61
3   apple  high     86
4  banana   low     28
5   melon  high      2


### Решение:

In [268]:
result = pandas.merge(first_source, second_source, how="inner", left_on=['fruit', 'weight'], right_on=['frukt', 'ves'],
                      suffixes=('_df1', '_df2'))
print(result)

   fruit weight  price_df1  frukt  ves  price_df2
0  apple    low         81  apple  low         22
1  apple    low         48  apple  low         22
2  apple    low         80  apple  low         22


## Задача №5:
Узнать частоту уникальных значений во всём DataFrame.

Ввод:

In [269]:
data_frame = pandas.DataFrame(numpy.random.randint(1, 10, 16).reshape(4, 4), columns=list('abcd'), index=list('1234'))
print(data_frame)

   a  b  c  d
1  7  9  4  7
2  6  4  1  3
3  8  4  5  5
4  2  7  8  2


### Решение:

In [270]:
frequency = pandas.value_counts(data_frame.values.ravel()).sort_values()
print(frequency)

9    1
6    1
1    1
3    1
8    2
5    2
2    2
7    3
4    3
Name: count, dtype: int64


## Задача №6:
Создать новый столбец, который содержит номера ближайших по евклидовому расстоянию столбцов.

Ввод:

In [271]:
data_frame = pandas.DataFrame(numpy.random.randint(1, 100, 16).reshape(4, 4), columns=list('abcd'), index=list('1234'))
print(data_frame)

    a   b   c   d
1  55  42   3  85
2  92   2  13  50
3  31  65  67  97
4  71  94  84  69


Ожидаемый результат:

In [272]:
expected = pandas.DataFrame({'e': [51, 63, 7, 6],
                             'f': [57, 5, 63, 31],
                             'g': [11, 81, 98, 29],
                             'h': [15, 48, 88, 37],
                             'row': ['c', 'a', 'a', 'c'],
                             'dist': [122.0, 94.0, 122.0, 92.0]
                             },
                            index=list('abcd')
                            )
print(expected)

    e   f   g   h row   dist
a  51  57  11  15   c  122.0
b  63   5  81  48   a   94.0
c   7  63  98  88   a  122.0
d   6  31  29  37   c   92.0


### Решение:

In [273]:
nearest_row = list()
nearest_dist = list()

for index, row in data_frame.iterrows():
    nearest = dict()
    for temp, remaining in (rest := data_frame.drop(index)).iterrows():
        nearest.update({temp: numpy.round(numpy.linalg.norm(row.values - remaining.values))})
    # Может я не до конца понимаю предмет задачи, но в условии "номера ближайших",
    # почему в эталонном решении max()...
    nearest_row.append(min(nearest, key=nearest.get))
    nearest_dist.append(min(nearest.values()))

data_frame['row'] = nearest_row
data_frame['dist'] = nearest_dist

print(data_frame)

    a   b   c   d row  dist
1  55  42   3  85   2  66.0
2  92   2  13  50   1  66.0
3  31  65  67  97   4  59.0
4  71  94  84  69   3  59.0


# Задачи по NumPy

## Задача №7:
Как поменять местами две строки в двумерном массиве NumPy? Поменяйте местами строки 1 и 3 массива a.

Ввод:

In [274]:
array = numpy.arange(9).reshape(3,3)
print(array, end='\n\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]]



In [276]:
temp_a = array.copy()

# Классический подход
temp = temp_a[-1]
temp_a[0] = temp_a [-1]
temp_a[-1] = temp
print(temp_a, end='\n\n')

# Эталон:
var = array[[2, 1, 0], :]
print(var)

[[6 7 8]
 [3 4 5]
 [6 7 8]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]
